app:
  name: "web_app"    # 项目名称
  mode: "dev"        # 模式
  port: 8082         # 端口

log:
  level: "debug"                    # 日志级别: debug/info/warn/error
  format: "json"                    # 日志格式: json/text/console
  filename: "logs/web_app.log"      # 主日志文件
  max_size: 100                     # 单个日志文件最大大小(MB)
  max_backups: 30                   # 保留旧日志文件数量
  max_age: 30                       # 保留旧日志天数
  compress: true                    # 是否压缩旧日志文件

mysql:
  host: "127.0.0.1"        # 主机
  port: 13306               # 端口
  user: "root"             # 用户名
  password: "123456"       # 密码
  database: "web_app"      # 数据库
  max_open_conns: 100      # 最大连接数
  max_idle_conns: 20       # 最大空闲连接数

redis:
  host: "127.0.0.1"        # 主机
  port: 16379               # 端口
  password: ""             # 密码 (如果Redis没有设置密码，请保持为空)
  database: 0              # 数据库
  pool_size: 100           # 连接池大小

snowflake:
  machine_id: 1            # 机器ID (分布式部署时每个实例使用不同的ID，范围：0-1023)

elasticsearch:
  url: "http://127.0.0.1:9200"  # Elasticsearch地址
  index: "bullbell_topics"       # 索引名称
  sniff: false                   # 是否开启嗅探 (单节点设置为false)